/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.usfirst.frc.team1492.robot;

public interface pixyConstants {
  public final static int PIXY_MIN_X = pixyJNI.PIXY_MIN_X_get();
  public final static int PIXY_MAX_X = pixyJNI.PIXY_MAX_X_get();
  public final static int PIXY_MIN_Y = pixyJNI.PIXY_MIN_Y_get();
  public final static int PIXY_MAX_Y = pixyJNI.PIXY_MAX_Y_get();
}
